knieriem latest starting point
https://github.com/knieriem/openocd-efm32-series2

this works for me to _flash_ via their command line

```
karlp@beros:~/src/openocd-git (master *)$ /home/karlp/src/openocd-git/src/openocd -s /home/karlp/src/openocd-git/tcl -f interface/jlink.cfg -c 'adapter serial 440183576'       -c 'transport select swd'       -f target/efm32s2.cfg -c init -c halt   -c 'flash probe 0'      -c 'flash banks'        -c 'flash list'         -c 'flash write_image erase efr32-tboard-blink-500ms-raw.bin'           -c exit
Open On-Chip Debugger 0.11.0+dev-00635-g7c6d379cf-dirty (2022-04-11-20:11)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
swd
efm32s2_dci_read_se_status
Info : Silicon Labs J-Link OB compiled Mar 11 2021 14:26:57
Info : Hardware version: 1.00
Info : VTarget = 2.985 V
Info : clock speed 1000 kHz
Info : SWD DPIDR 0x6ba02477
Info : [efm32s2.cpu] Cortex-M33 r0p4 processor detected
Info : [efm32s2.cpu] target has 8 breakpoints, 4 watchpoints
Info : starting gdb server for efm32s2.cpu on 3333
Info : Listening on port 3333 for gdb connections
target halted due to debug-request, current mode: Thread
xPSR: 0x61000000 pc: 0x00002b3e psp: 0x20001608
Info : detected part: BG22C224, rev 6
Info : flash size = 512kbytes
Info : flash page size = 8192bytes
flash 'efm32s2' found at 0x00000000

{name efm32s2.flash driver efm32s2 base 0 size 524288 bus_width 0 chip_width 0 target efm32s2.cpu}
auto erase enabled
wrote 24576 bytes from file efr32-tboard-blink-500ms-raw.bin in 0.673072s (35.657 KiB/s)
```

This leaves it halted, no problem.

but it does _not_ work to flash via GDB!

```
(gdb) load
Error erasing flash with vFlashErase packet

karlp@beros:~/src/openocd-git (master *)$ /home/karlp/src/openocd-git/src/openocd -s /home/karlp/src/openocd-git/tcl -f interface/jlink.cfg -c 'adapter serial 440183576'       -c 'transport select swd'       -f target/efm32s2.cfg
Open On-Chip Debugger 0.11.0+dev-00635-g7c6d379cf-dirty (2022-04-11-20:11)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
swd
efm32s2_dci_read_se_status
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : Silicon Labs J-Link OB compiled Mar 11 2021 14:26:57
Info : Hardware version: 1.00
Info : VTarget = 2.985 V
Info : clock speed 1000 kHz
Info : SWD DPIDR 0x6ba02477
Info : [efm32s2.cpu] Cortex-M33 r0p4 processor detected
Info : [efm32s2.cpu] target has 8 breakpoints, 4 watchpoints
Info : starting gdb server for efm32s2.cpu on 3333
Info : Listening on port 3333 for gdb connections
Info : accepting 'gdb' connection on tcp/3333
target halted due to debug-request, current mode: Thread
xPSR: 0x61000000 pc: 0x00002b44 psp: 0x20001608
Info : detected part: BG22C224, rev 6
Info : flash size = 512kbytes
Info : flash page size = 8192bytes
Info : SWD DPIDR 0x6ba02477
Error: timed out while waiting for target halted
Error executing event gdb-flash-erase-start on target efm32s2.cpu:
TARGET: efm32s2.cpu - Not halted
Error: Target not halted
Error: failed erasing sectors 0 to 2
Error: flash_erase returned -304
Info : Halt timed out, wake up GDB.
^Cshutdown command invoked

karlp@beros:~/src/openocd-git (master *)$
```

Change-Id: Ib858c348b46f4a7fafa655890ff08e6a100e5dc3