HACK: handle ST-LINK not really available after resume?
If it's not available, but you have a tpiu configured, the cleanup path
doesn't validate the stlink handle still being valid.

d3 log attached here for prosperity:
suspect the root cause is:
Debug: 167 25 stlink_usb.c:792 stlink_usb_error_check(): unknown/unexpected STLINK status code 0x5
Error: 168 25 stlink_usb.c:2959 stlink_usb_open(): init mode failed (unable to connect to the target)
Debug: 169 26 stlink_usb.c:1323 stlink_usb_exit_mode(): MODE: 0x02

$ openocd -d3
Open On-Chip Debugger 0.11.0 (2021-09-01-18:12)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
User : 13 2 options.c:63 configuration_output_handler(): debug_level: 3
User : 14 2 options.c:63 configuration_output_handler():
Debug: 15 2 options.c:244 add_default_dirs(): bindir=/home/karlp/.local/bin
Debug: 16 2 options.c:245 add_default_dirs(): pkgdatadir=/home/karlp/.local/share/openocd
Debug: 17 2 options.c:246 add_default_dirs(): exepath=/home/karlp/.local/bin
Debug: 18 2 options.c:247 add_default_dirs(): bin2data=../share/openocd
Debug: 19 2 configuration.c:42 add_script_search_dir(): adding /home/karlp/.config/openocd
Debug: 20 2 configuration.c:42 add_script_search_dir(): adding /home/karlp/.openocd
Debug: 21 2 configuration.c:42 add_script_search_dir(): adding /home/karlp/.local/bin/../share/openocd/site
Debug: 22 3 configuration.c:42 add_script_search_dir(): adding /home/karlp/.local/bin/../share/openocd/scripts
Debug: 23 3 configuration.c:97 find_file(): found openocd.cfg
Debug: 24 3 configuration.c:97 find_file(): found /home/karlp/.local/bin/../share/openocd/scripts/interface/stlink.cfg
Debug: 25 3 command.c:146 script_debug(): command - adapter driver hla
Debug: 27 3 command.c:146 script_debug(): command - hla_layout stlink
Debug: 29 3 hla_interface.c:242 hl_interface_handle_layout_command(): hl_interface_handle_layout_command
Debug: 30 3 command.c:146 script_debug(): command - hla_device_desc ST-LINK
Debug: 32 3 hla_interface.c:216 hl_interface_handle_device_desc_command(): hl_interface_handle_device_desc_command
Debug: 33 3 command.c:146 script_debug(): command - hla_vid_pid 0x0483 0x3744 0x0483 0x3748 0x0483 0x374b 0x0483 0x374d 0x0483 0x374e 0x0483 0x374f 0x0483 0x3752 0x0483 0x3753
Debug: 35 3 configuration.c:97 find_file(): found /home/karlp/.local/bin/../share/openocd/scripts/target/stm32wbx.cfg
Debug: 36 3 configuration.c:97 find_file(): found /home/karlp/.local/bin/../share/openocd/scripts/target/swj-dp.tcl
Debug: 37 3 command.c:146 script_debug(): command - transport select
Info : 38 3 transport.c:275 jim_transport_select(): auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.
Debug: 39 3 hla_transport.c:205 hl_swd_transport_select(): hl_swd_transport_select
Debug: 40 4 configuration.c:97 find_file(): found /home/karlp/.local/bin/../share/openocd/scripts/mem_helper.tcl
Debug: 41 4 command.c:146 script_debug(): command - add_usage_text mrw address
Debug: 43 4 command.c:1115 help_add_command(): added 'mrw' help text
Debug: 44 4 command.c:146 script_debug(): command - add_help_text mrw Returns value of word in memory.
Debug: 46 4 command.c:1128 help_add_command(): added 'mrw' help text
Debug: 47 4 command.c:146 script_debug(): command - add_usage_text mrh address
Debug: 49 4 command.c:1115 help_add_command(): added 'mrh' help text
Debug: 50 4 command.c:146 script_debug(): command - add_help_text mrh Returns value of halfword in memory.
Debug: 52 4 command.c:1128 help_add_command(): added 'mrh' help text
Debug: 53 4 command.c:146 script_debug(): command - add_usage_text mrb address
Debug: 55 4 command.c:1115 help_add_command(): added 'mrb' help text
Debug: 56 4 command.c:146 script_debug(): command - add_help_text mrb Returns value of byte in memory.
Debug: 58 4 command.c:1128 help_add_command(): added 'mrb' help text
Debug: 59 4 command.c:146 script_debug(): command - add_usage_text mmw address setbits clearbits
Debug: 61 4 command.c:1115 help_add_command(): added 'mmw' help text
Debug: 62 4 command.c:146 script_debug(): command - add_help_text mmw Modify word in memory. new_val = (old_val & ~clearbits) | setbits;
Debug: 64 4 command.c:1128 help_add_command(): added 'mmw' help text
Debug: 65 4 command.c:146 script_debug(): command - transport select
Debug: 66 4 command.c:146 script_debug(): command - transport select
Debug: 67 4 command.c:146 script_debug(): command - transport select
Debug: 68 4 command.c:146 script_debug(): command - swd newdap stm32wbx cpu -irlen 4 -ircapture 0x1 -irmask 0xf -expected-id 0x6ba02477
Debug: 69 4 hla_tcl.c:110 jim_hl_newtap_cmd(): Creating New Tap, Chip: stm32wbx, Tap: cpu, Dotted: stm32wbx.cpu, 8 params
Debug: 70 4 hla_tcl.c:121 jim_hl_newtap_cmd(): Processing option: -irlen
Debug: 71 4 hla_tcl.c:121 jim_hl_newtap_cmd(): Processing option: -ircapture
Debug: 72 4 hla_tcl.c:121 jim_hl_newtap_cmd(): Processing option: -irmask
Debug: 73 4 hla_tcl.c:121 jim_hl_newtap_cmd(): Processing option: -expected-id
Debug: 74 4 core.c:1484 jtag_tap_init(): Created Tap: stm32wbx.cpu @ abs position 0, irlen 0, capture: 0x0 mask: 0x0
Debug: 75 4 command.c:146 script_debug(): command - dap create stm32wbx.dap -chain-position stm32wbx.cpu
Debug: 76 4 command.c:146 script_debug(): command - transport select
Debug: 77 4 command.c:146 script_debug(): command - target create stm32wbx.cpu cortex_m -endian little -dap stm32wbx.dap
Info : 78 4 target.c:5668 target_create(): The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Debug: 79 4 hla_target.c:203 adapter_target_create(): adapter_target_create
Debug: 80 4 hla_target.c:173 adapter_init_arch_info(): adapter_init_arch_info
Debug: 81 4 command.c:375 register_command(): command 'rtt' is already registered in '<global>' context
Debug: 82 5 command.c:146 script_debug(): command - stm32wbx.cpu configure -work-area-phys 0x20000000 -work-area-size 0x10000 -work-area-backup 0
Debug: 83 5 target.c:2172 target_free_all_working_areas_restore(): freeing all working areas
Debug: 84 5 target.c:2172 target_free_all_working_areas_restore(): freeing all working areas
Debug: 85 5 target.c:2172 target_free_all_working_areas_restore(): freeing all working areas
Debug: 86 5 command.c:146 script_debug(): command - flash bank stm32wbx.flash stm32l4x 0 0 0 0 stm32wbx.cpu
Debug: 88 5 tcl.c:1319 handle_flash_bank_command(): 'stm32l4x' driver usage field missing
Debug: 89 5 command.c:146 script_debug(): command - adapter speed 500
Debug: 91 5 core.c:1822 jtag_config_khz(): handle jtag khz
Debug: 92 5 core.c:1785 adapter_khz_to_speed(): convert khz to interface specific speed value
Debug: 93 5 core.c:1785 adapter_khz_to_speed(): convert khz to interface specific speed value
Debug: 94 5 command.c:146 script_debug(): command - adapter srst delay 100
Debug: 96 5 command.c:146 script_debug(): command - transport select
Debug: 97 5 command.c:146 script_debug(): command - reset_config srst_nogate
Debug: 99 5 command.c:146 script_debug(): command - transport select
Debug: 100 5 command.c:146 script_debug(): command - stm32wbx.cpu configure -event reset-init
    # CPU comes out of reset with MSI_ON | MSI_RDY | MSI Range 4 MHz.
    # Configure system to use MSI 24 MHz clock, compliant with VOS default Range1.
    # 2 WS compliant with VOS=Range1 and 24 MHz.
    mmw 0x58004000 0x00000102 0  ;# FLASH_ACR |= PRFTBE | 2(Latency)
    mmw 0x58000000 0x00000091 0  ;# RCC_CR = MSI_ON | MSI Range 24 MHz
    # Boost JTAG frequency
    adapter speed 4000

Debug: 101 5 command.c:146 script_debug(): command - stm32wbx.cpu configure -event reset-start
    # Reset clock is MSI (4 MHz)
    adapter speed 500

Debug: 102 5 command.c:146 script_debug(): command - stm32wbx.cpu configure -event examine-end
    # Enable debug during low power modes (uses more power)
    # DBGMCU_CR |= DBG_STANDBY | DBG_STOP | DBG_SLEEP
    mmw 0xE0042004 0x00000007 0

    # Stop watchdog counters during halt
    # DBGMCU_APB1_FZR1 |= DBG_IWDG_STOP | DBG_WWDG_STOP
    mmw 0xE004203C 0x00001800 0

Debug: 103 5 command.c:146 script_debug(): command - stm32wbx.cpu configure -event trace-config
    # Set TRACE_IOEN; TRACE_MODE is set to async; when using sync
    # change this value accordingly to configure trace pins
    # assignment
    mmw 0xE0042004 0x00000020 0

Debug: 104 5 command.c:146 script_debug(): command - bindto 0.0.0.0
Debug: 106 5 command.c:146 script_debug(): command - tpiu config internal :3443 uart off 64000000
Info : 108 5 server.c:311 add_service(): Listening on port 3443 for armv7m_trace connections
User : 109 6 command.c:694 command_run_line(): openocd.cfg:13: Error: Can't find /home/karlp/src/cbms3/smartfw32/trace-helpers.cfg
in procedure 'script'
at file "embedded:startup.tcl", line 26
at file "openocd.cfg", line 13
Info : 110 6 server.c:311 add_service(): Listening on port 6666 for tcl connections
Info : 111 6 server.c:311 add_service(): Listening on port 4444 for telnet connections
Debug: 112 6 command.c:146 script_debug(): command - init
Debug: 114 6 command.c:146 script_debug(): command - target init
Debug: 116 6 command.c:146 script_debug(): command - target names
Debug: 117 6 command.c:146 script_debug(): command - stm32wbx.cpu cget -event gdb-flash-erase-start
Debug: 118 6 command.c:146 script_debug(): command - stm32wbx.cpu configure -event gdb-flash-erase-start reset init
Debug: 119 6 command.c:146 script_debug(): command - stm32wbx.cpu cget -event gdb-flash-write-end
Debug: 120 6 command.c:146 script_debug(): command - stm32wbx.cpu configure -event gdb-flash-write-end reset halt
Debug: 121 6 command.c:146 script_debug(): command - stm32wbx.cpu cget -event gdb-attach
Debug: 122 6 command.c:146 script_debug(): command - stm32wbx.cpu configure -event gdb-attach halt 1000
Debug: 123 6 target.c:1639 handle_target_init_command(): Initializing targets...
Debug: 124 6 hla_target.c:193 adapter_init_target(): adapter_init_target
Debug: 125 6 semihosting_common.c:99 semihosting_common_init():
Debug: 126 7 hla_interface.c:109 hl_interface_init(): hl_interface_init
Debug: 127 7 hla_layout.c:95 hl_layout_init(): hl_layout_init
Debug: 128 7 core.c:1785 adapter_khz_to_speed(): convert khz to interface specific speed value
Debug: 129 7 core.c:1789 adapter_khz_to_speed(): have interface set up
Debug: 130 7 core.c:1785 adapter_khz_to_speed(): convert khz to interface specific speed value
Debug: 131 7 core.c:1789 adapter_khz_to_speed(): have interface set up
Info : 132 7 core.c:1565 adapter_init(): clock speed 500 kHz
Debug: 133 7 openocd.c:143 handle_init_command(): Debug Adapter init complete
Debug: 134 7 command.c:146 script_debug(): command - transport init
Debug: 136 7 transport.c:229 handle_transport_init(): handle_transport_init
Debug: 137 7 hla_transport.c:156 hl_transport_init(): hl_transport_init
Debug: 138 7 hla_transport.c:173 hl_transport_init(): current transport hla_swd
Debug: 139 7 hla_interface.c:42 hl_interface_open(): hl_interface_open
Debug: 140 7 hla_layout.c:40 hl_layout_open(): hl_layout_open
Debug: 141 7 stlink_usb.c:2819 stlink_usb_open(): stlink_usb_open
Debug: 142 7 stlink_usb.c:2831 stlink_usb_open(): transport: 4 vid: 0x0483 pid: 0x3744 serial:
Debug: 143 7 stlink_usb.c:2831 stlink_usb_open(): transport: 4 vid: 0x0483 pid: 0x3748 serial:
Debug: 144 7 stlink_usb.c:2831 stlink_usb_open(): transport: 4 vid: 0x0483 pid: 0x374b serial:
Debug: 145 7 stlink_usb.c:2831 stlink_usb_open(): transport: 4 vid: 0x0483 pid: 0x374d serial:
Debug: 146 7 stlink_usb.c:2831 stlink_usb_open(): transport: 4 vid: 0x0483 pid: 0x374e serial:
Debug: 147 7 stlink_usb.c:2831 stlink_usb_open(): transport: 4 vid: 0x0483 pid: 0x374f serial:
Debug: 148 7 stlink_usb.c:2831 stlink_usb_open(): transport: 4 vid: 0x0483 pid: 0x3752 serial:
Debug: 149 7 stlink_usb.c:2831 stlink_usb_open(): transport: 4 vid: 0x0483 pid: 0x3753 serial:
Info : 150 23 stlink_usb.c:1098 stlink_usb_version(): STLINK V2J37M27 (API v2) VID:PID 0483:374B
Debug: 151 23 stlink_usb.c:1323 stlink_usb_exit_mode(): MODE: 0x02
Info : 152 23 stlink_usb.c:1134 stlink_usb_check_voltage(): Target voltage: 3.260614
Debug: 153 23 stlink_usb.c:1391 stlink_usb_init_mode(): MODE: 0x02
Debug: 154 23 stlink_usb.c:2606 stlink_dump_speed_map(): Supported clock speeds are:
Debug: 155 23 stlink_usb.c:2609 stlink_dump_speed_map(): 4000 kHz
Debug: 156 23 stlink_usb.c:2609 stlink_dump_speed_map(): 1800 kHz
Debug: 157 23 stlink_usb.c:2609 stlink_dump_speed_map(): 1200 kHz
Debug: 158 23 stlink_usb.c:2609 stlink_dump_speed_map(): 950 kHz
Debug: 159 23 stlink_usb.c:2609 stlink_dump_speed_map(): 480 kHz
Debug: 160 23 stlink_usb.c:2609 stlink_dump_speed_map(): 240 kHz
Debug: 161 23 stlink_usb.c:2609 stlink_dump_speed_map(): 125 kHz
Debug: 162 23 stlink_usb.c:2609 stlink_dump_speed_map(): 100 kHz
Debug: 163 23 stlink_usb.c:2609 stlink_dump_speed_map(): 50 kHz
Debug: 164 23 stlink_usb.c:2609 stlink_dump_speed_map(): 25 kHz
Debug: 165 23 stlink_usb.c:2609 stlink_dump_speed_map(): 15 kHz
Debug: 166 23 stlink_usb.c:2609 stlink_dump_speed_map(): 5 kHz
Debug: 167 25 stlink_usb.c:792 stlink_usb_error_check(): unknown/unexpected STLINK status code 0x5
Error: 168 25 stlink_usb.c:2959 stlink_usb_open(): init mode failed (unable to connect to the target)
Debug: 169 26 stlink_usb.c:1323 stlink_usb_exit_mode(): MODE: 0x02
Debug: 170 26 hla_layout.c:47 hl_layout_open(): failed
Debug: 171 26 command.c:628 run_command(): Command 'transport init' failed with error code -4
User : 172 26 command.c:694 command_run_line(): openocd.cfg:13: Error:
in procedure 'script'
at file "embedded:startup.tcl", line 26
at file "openocd.cfg", line 13
Debug: 173 26 command.c:628 run_command(): Command 'init' failed with error code -4
User : 174 26 command.c:694 command_run_line(): openocd.cfg:13: Error:
in procedure 'script'
at file "embedded:startup.tcl", line 26
at file "openocd.cfg", line 13
Info : 175 26 stlink_usb.c:3014 stlink_config_trace(): ST-LINK not actually attached, ignoring attempt to set enabled: false
Error: 176 26 armv7m_trace.c:118 armv7m_trace_tpiu_config(): Trace port frequency is 0, can't enable TPIU
Debug: 177 26 target.c:2172 target_free_all_working_areas_restore(): freeing all working areas
Debug: 178 26 hla_interface.c:117 hl_interface_quit(): hl_interface_quit
karlp@beros:~/src/red-heart (rtic-style)$

Change-Id: I7bbb02bf93d835395b6c8340e4cc114c431ad8e5